USE [master]
GO

/****** Object:  Database [lucasseABETOtTBI]    Script Date: 28/11/2013 10:45:48 ******/
CREATE DATABASE [lucasseABETOtTBI]
GO

ALTER DATABASE [lucasseABETOtTBI] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [lucasseABETOtTBI].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [lucasseABETOtTBI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET ARITHABORT OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [lucasseABETOtTBI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [lucasseABETOtTBI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [lucasseABETOtTBI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET  DISABLE_BROKER 
GO

ALTER DATABASE [lucasseABETOtTBI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [lucasseABETOtTBI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [lucasseABETOtTBI] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [lucasseABETOtTBI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET RECOVERY FULL 
GO

ALTER DATABASE [lucasseABETOtTBI] SET  MULTI_USER 
GO

ALTER DATABASE [lucasseABETOtTBI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [lucasseABETOtTBI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [lucasseABETOtTBI] SET  READ_WRITE 
GO

